computer_terms = [
    "Threadripper",
    "Algorithm",
    "Application",
    "ASCII",
    "Assembler",
    "Bandwidth",
    "Binary",
    "Bit",
    "Byte",
    "Cache",
    "Callback",
    "Captcha",
    "Character",
    "Clipboard",
    "Cloud",
    "Cluster",
    "Compiler",
    "Compression",
    "Cookie",
    "CPU",
    "Cryptography",
    "CSS",
    "Database",
    "Debugger",
    "Decryption",
    "DNS",
    "Driver",
    "Encryption",
    "Firewall",
    "Firmware",
    "FTP",
    "Gateway",
    "Git",
    "GUI",
    "Hash",
    "Heap",
    "HTML",
    "HTTP",
    "HTTPS",
    "Hyperlink",
    "IDE",
    "IP Address",
    "Java",
    "JavaScript",
    "Kernel",
    "Keyword",
    "Latency",
    "Linux",
    "Logic Gate",
    "MAC Address",
    "Malware",
    "Metadata",
    "Multithreading",
    "Node",
    "Object",
    "Operating System",
    "Overflow",
    "Packet",
    "Pixel",
    "Pointer",
    "Protocol",
    "Query",
    "Queue",
    "RAM",
    "Recursion",
    "Repository",
    "Router",
    "Runtime",
    "Script",
    "SDK",
    "Search Engine",
    "Server",
    "Shell",
    "Socket",
    "Software",
    "SQL",
    "Stack",
    "Stream",
    "String",
    "Subroutine",
    "Syntax",
    "TCP/IP",
    "Thread",
    "Token",
    "URL",
    "Variable",
    "Vector",
    "Virtualization",
    "Virus",
    "VPN",
    "Web Browser",
    "Web Server",
    "WiFi",
    "XML"
]

